# Generated by Django 6.0.3 on 2026-03-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('processing', 'processing'), ('shipped', 'shipped'), ('delivred', 'delivred')], default='pending', max_length=20, null=True),
        ),
    ]
